# -*- coding: utf-8 -*-
"""Untitled51.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VV1IKgAPhGLuvVqLyKuAp-IEilbrFXrB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Load Dataset (Assuming a CSV with 'label' and 'text' columns)
# Note: You can download 'spam.csv' from Kaggle or use a URL
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
df = pd.read_csv(url, sep='\t', names=['label', 'text'])

# 2. Preprocessing: Convert labels to numbers (ham=0, spam=1)
df['label_num'] = df.label.map({'ham': 0, 'spam': 1})

# 3. Split data into Training and Testing
X_train, X_test, y_train, y_test = train_test_split(df['text'], df['label_num'], test_size=0.2, random_state=42)

# 4. Feature Extraction: Convert text to numbers
vectorizer = TfidfVectorizer(stop_words='english')
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# 5. Build and Train Model (Naive Bayes)
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

# 6. Predictions
predictions = model.predict(X_test_tfidf)

# --- GRAPH GENERATION ---

# Graph 1: Data Distribution (Pie Chart)
plt.figure(figsize=(6,6))
df['label'].value_counts().plot(kind='pie', autopct='%1.1f%%', colors=['skyblue', 'salmon'])
plt.title('Distribution of Spam vs Ham')
plt.savefig('distribution_graph.png') # Saves screenshot for your email
plt.show()

# Graph 2: Confusion Matrix (Heatmap)
cm = confusion_matrix(y_test, predictions)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Ham', 'Spam'], yticklabels=['Ham', 'Spam'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Spam Detection Confusion Matrix')
plt.savefig('confusion_matrix.png') # Saves screenshot for your email
plt.show()

print(f"Accuracy Score: {accuracy_score(y_test, predictions) * 100:.2f}%")

from google.colab import drive
drive.mount('/content/drive')